version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.0
workflows:
  build:
    jobs:
      - cypress/install:
          build: "yarn"
      - cypress/run:
          record: false
          parallel: false
          parallelism: 10
