version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: yarn test  --ci --reporters=jest-junit
      - store_artifacts:
          path: ./test-results
      - store_test_results:
          path: ./test-results
