name: Acceptance Tests
on:
  push:
    branches: [master, main]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  codeconcept-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: yarn install
      - name: Run test
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm run codeceptjs-test
